name: bundle
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  bundle:
    name: release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set the release related variables
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          # Release tags.
          echo BUNDLE_TAG="${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        else
          echo BUNDLE_TAG="$(git describe --tags --always)" >> $GITHUB_ENV
        fi
        echo BUNDLE_REPO="quay.io/tflannag/combo" >> $GITHUB_ENV

    - name: Print out relevant environment variables
      run: |
        echo "${{ env.BUNDLE_REPO }}"
        echo "${{ env.BUNDLE_TAG }}"

    - name: Build and push bundle
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile.plainbundle
        tags: ${{ env.BUNDLE_REPO }}:${{ env.BUNDLE_TAG }}
        github-token: ${{ github.token }}
